---
title: "International Bitterness Unit (IBU) Analysis"
author: "Jaclyn Ann Coate & Huy Hoang Nguyen"
date: "`r Sys.Date()`"
output: 
  revealjs::revealjs_presentation:
    transition: slide
    keep_md: true
    theme: simple
    highlight: pygments
    center: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{r Library set up}
library(tidyverse)
library(ggthemes)
library(dplyr)
library(highcharter)
library(ggmap)
library(ggExtra)
library(treemapify)
library(maps)
library(naniar)
library(knitr)
library(revealjs)
```

```{r Create data sets for reference in this file}
breweries <- read.csv("https://raw.githubusercontent.com/BivinSadler/MDS-6306-Doing-Data-Science-Fall-2019/master/Unit%208%20and%209%20Case%20Study%201/Breweries.csv", header = TRUE, strip.white=TRUE)

beers <- read.csv("https://raw.githubusercontent.com/BivinSadler/MDS-6306-Doing-Data-Science-Fall-2019/master/Unit%208%20and%209%20Case%20Study%201/Beers.csv", header = TRUE)
#str(beers)
#glimpse(beers)

beers <-  beers %>% dplyr::rename( Brew_ID = Brewery_id)
#glimpse(beers)

breweries <- breweries %>% dplyr::rename(Name_Brew = Name)  
beers <- beers %>% dplyr::rename(Name_Beer = Name)

#glimpse(breweries)
#glimpse(beers)

brew.beer <- full_join(breweries, beers, by = "Brew_ID")
```

```{r Create Median IBU Data Set}
brew.beer.cleanIBU <- brew.beer %>% filter(!is.na(IBU))
```

```{r Group median IBU by State}
brew.beerIBU <- aggregate(brew.beer.cleanIBU$IBU, by=list(brew.beer.cleanIBU$State), FUN = median)
#glimpse(brew.beerIBU)
```

```{r Label Columns}
colnames(brew.beerIBU) <- c("State", "MedIBU")
#glimpse(brew.beerIBU)
```

```{r Sort data for column graph}
brew.beerIBU <- brew.beerIBU[order(brew.beerIBU$MedIBU),]
```

```{r Retain sorted order in the Plot}
brew.beerIBU$State <- factor(brew.beerIBU$State, levels = brew.beerIBU$State)
```

# Bitterness (IBU) Analysis
## Median IBU by State
```{r geom_bar chart of median IBU by State}
brew.beerIBU %>% ggplot(mapping = aes(x=State, y=MedIBU)) +
  geom_bar(stat = "identity", fill = "dark blue") +
  theme_excel_new() +
  theme(legend.position="none", axis.text.x = element_text(angle=65, vjust=0.6)) +
  ggtitle("Median IBU by State") + ylab("IBU") + xlab("State")
```

```{r Create key column for geo map to reference}
brew.beerIBU$code <- brew.beerIBU$State
#glimpse(brew.beerIBU)
#summary(brew.beerIBU)
#nrow(brew.beerIBU)
```

```{r Adding South Dakota 0 so it renders on GEO map even with a 0 value}
sd <- data.frame("SD", 0, "SD")
colnames(sd) <- c("State", "MedIBU", "code")
#sd
brew.beerIBU <- rbind(brew.beerIBU, sd)
```

```{r IBU: Create key column for geo map to reference}
breweryGeo <- data.frame(table(breweries$State))
colnames(breweryGeo) <- c("code", "Breweries")
```

## Median IBU by State
```{r IBU: hc geo map of Median IBU by State}
#glimpse(brew.beerIBU)
colorIBU <- hcmap("countries/us/us-all", data = brew.beerIBU, value = "MedIBU",
      joinBy = c("hc-a2", "code"), name = "IBU",
      dataLabels = list(enabled = TRUE, format = '{point.name}'),
      borderColor = "#FAFAFA", borderWidth = 0.1,
      tooltip = list(valueDecimals = 1)) 

hc_colorAxis(colorIBU, min = 18,
            max = 62,
            #type = 'logarithmic',
            minColor = '#ffffff',
            maxColor = '#000080',
            lineColor = 'black',
            lineWidth = .5
            )
```

```{r Max IBU by State}
#glimpse(brew.beer)
maxIBU <- data.frame(brew.beer[which.max(brew.beer$IBU),])
#maxIBU
```

```{r key column for geo map to reference}
maxIBU$code <- maxIBU$State
```

## Highest IBU
### Oregon at 138
```{r Geo map of Oregon, fig.width = 7, fig.height = 5}
colorMaxIBU <- hcmap("countries/us/us-all", data = maxIBU, value = "IBU",
      joinBy = c("hc-a2", "code"), name = "IBU",
      dataLabels = list(enabled = TRUE, format = '{point.name}'),
      borderColor = "#FAFAFA", borderWidth = 0.1,
      tooltip = list(valueDecimals = 1))

hc_colorAxis(colorMaxIBU, min = 18,
            max = 62,
            #type = 'logarithmic',
            minColor = '#ffffff',
            maxColor = '#000080',
            lineColor = 'black',
            lineWidth = .5
            )
```



## IBU Distribution

- 75% of the IBU falls between 30 - 43
- Higher than Budweiser's 7
```{r Boxplot of Median IBU distribution, fig.width = 7, fig.height = 5}
brew.beer.cleanIBU <- brew.beer %>% filter(!is.na(IBU))
MedianIBU <- brew.beer.cleanIBU %>% group_by(State) %>% summarise(medIBU = median(c(IBU)))
#summary(MedianIBU)

MedianIBU %>% ggplot(mapping = aes(y = medIBU)) +
  geom_boxplot(fill = "dark blue", color = "black") +
  theme_excel_new() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  ggtitle("Median IBU Summary Statistics") + ylab("Median IBU") + xlab("")
```